---
sudo: required

env:
  - distribution: packetferret/ansible-vxlan-evpn-for-campus
    version: 0.0.3

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'

script:
  - 'make build'
  - 'make config'
